name: tikwiki_algo
description: Feed orchestration, scoring, and diversity ranking for Tikwiki.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.5

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
